// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oonibdzxeqkgokdclsde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vbmliZHp4ZXFrZ29rZGNsc2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODkzOTgsImV4cCI6MjA2NDQ2NTM5OH0.fuqCY8o4fK2Ym5z2z_CE2LWTK7t4HwS29Q-bXBXnfFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);